"use client"

<<<<<<< HEAD
import type React from "react"

=======
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
<<<<<<< HEAD
import { ChevronLeft, Search, Plus, Upload, X } from "lucide-react"
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { useToast } from "@/components/ui/use-toast"
=======
import { Badge } from "@/components/ui/badge"
import { ChevronLeft, Search, Plus, Filter, Eye, Edit, Trash2 } from "lucide-react"
import Link from "next/link"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
<<<<<<< HEAD
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage, FormDescription } from "@/components/ui/form"
import { FormSection } from "@/components/forms/FormSection"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Skeleton } from "@/components/ui/skeleton"
import { Badge } from "@/components/ui/badge"

// Define the vaccinator form schema with Zod
const vaccinatorFormSchema = z
  .object({
    // Basic information
    vaccinator_id: z.string().uuid().optional(), // Primary key, auto-generated by Supabase
    firstName: z.string().min(1, "First name is required"),
    lastName: z.string().min(1, "Last name is required"),
    email: z.string().email("Please enter a valid email address").toLowerCase(),
    phone: z
      .string()
      .min(10, "Phone number must be at least 10 digits")
      .regex(/^\+?[0-9\s\-()]+$/, "Invalid phone number format"),

    // Professional details
    departmentId: z.string().min(1, "Please select a valid department"), // Foreign key to departments table
    professionalId: z.string().min(1, "Professional ID/License is required"),

    // System fields - using lowercase values to match the database constraint
    status: z.enum(["active", "inactive", "suspended"]).default("active"),

    // Authentication (handled separately in auth tables)
    password: z
      .string()
      .min(8, "Password must be at least 8 characters")
      .regex(/[A-Z]/, "Password must contain at least one uppercase letter")
      .regex(/[0-9]/, "Password must contain at least one number")
      .regex(/[^A-Za-z0-9]/, "Password must contain at least one special character"),
    confirmPassword: z.string().min(1, "Please confirm your password"),

    // Simplified availability fields
    weekdayAvailability: z.boolean().default(true),
    weekendAvailability: z.boolean().default(false),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
  })

type VaccinatorFormValues = z.infer<typeof vaccinatorFormSchema>

// Define the vaccinator table structure - updated for new schema
interface StaffMember {
  id?: string // For frontend compatibility
  vaccinator_id: string // Primary key in the database
  auth_id?: string
=======
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { FormSection } from "@/components/forms/FormSection"
import { useToast } from "@/components/ui/use-toast"
import { Skeleton } from "@/components/ui/skeleton"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"

// Force dynamic rendering to prevent prerender errors
export const dynamic = "force-dynamic"

// Define the vaccinator form schema
const vaccinatorFormSchema = z.object({
  image_url: z.string().optional(),
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().min(1, "Last name is required"),
  email: z.string().email("Please enter a valid email address"),
  phone: z.string().min(10, "Phone number must be at least 10 digits"),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  license_number: z.string().min(1, "License number is required"),
  specialization: z.string().min(1, "Specialization is required"),
  department: z.string().min(1, "Department is required"),
  availability: z.string().optional(),
  username: z.string().min(3, "Username must be at least 3 characters"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  status: z.enum(["active", "inactive"]).default("active"),
})

type VaccinatorFormValues = z.infer<typeof vaccinatorFormSchema>

// Define the vaccinator structure
interface StaffMember {
  id: string
  image_url: string | null
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
  first_name: string
  last_name: string
  email: string
  phone: string
<<<<<<< HEAD
  department: string
  professional_id: string
  status: string
  weekday_availability: boolean
  weekend_availability: boolean
  profile_image_url?: string
=======
  address: string | null
  city: string | null
  state: string | null
  zip: string | null
  license_number: string
  specialization: string
  department: string
  availability: string | null
  username: string
  password?: string
  status: string
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
  created_at: string
  updated_at: string
}

export default function VaccinatorManagement() {
  const [searchQuery, setSearchQuery] = useState("")
<<<<<<< HEAD
  const [showAddForm, setShowAddForm] = useState(false)
  const [imagePreview, setImagePreview] = useState<string | null>(null)
  const { toast } = useToast()
=======
  const [filterStatus, setFilterStatus] = useState("all")
  const [dialogOpen, setDialogOpen] = useState(false)
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [vaccinators, setVaccinators] = useState<StaffMember[]>([])
  const [error, setError] = useState<string | null>(null)
<<<<<<< HEAD

  // Initialize the form with React Hook Form
  const form = useForm<VaccinatorFormValues>({
    resolver: zodResolver(vaccinatorFormSchema),
    defaultValues: {
      firstName: "",
      lastName: "",
      email: "",
      phone: "",
      departmentId: "",
      professionalId: "",
      status: "active", // Using lowercase to match the database constraint
      weekdayAvailability: true,
      weekendAvailability: false,
      password: "",
      confirmPassword: "",
    },
  })

  // Fetch vaccinators from Supabase
=======
  const { toast } = useToast()

  // Initialize the form
  const form = useForm<VaccinatorFormValues>({
    resolver: zodResolver(vaccinatorFormSchema),
    defaultValues: {
      image_url: "",
      first_name: "",
      last_name: "",
      email: "",
      phone: "",
      address: "",
      city: "",
      state: "",
      zip: "",
      license_number: "",
      specialization: "",
      department: "",
      availability: "",
      username: "",
      password: "",
      status: "active",
    },
  })

  // Fetch vaccinators from the API
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
  const fetchVaccinators = async () => {
    try {
      setIsLoading(true)
      setError(null)
      console.log("Fetching vaccinators...")

<<<<<<< HEAD
      // Use fetch API instead of direct Supabase client to avoid client-side RLS issues
      const response = await fetch("/api/staff/list")

      if (!response.ok) {
        const contentType = response.headers.get("content-type")
        if (contentType && contentType.includes("application/json")) {
          const errorData = await response.json()
          throw new Error(errorData.error || `Failed to fetch vaccinators (${response.status})`)
        } else {
          throw new Error(`Failed to fetch vaccinators (${response.status})`)
        }
      }

      const result = await response.json()
      console.log("Fetched vaccinators:", result.data)

      if (result.data) {
        setVaccinators(result.data)
      }
    } catch (error: any) {
      console.error("Error fetching vaccinators:", error)
      setError(error.message || "Failed to load vaccinators")
      toast({
        title: "Error",
        description: error.message || "Failed to load vaccinators. Please refresh the page.",
        variant: "destructive",
      })
=======
      const response = await fetch("/api/staff/list")
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const result = await response.json()
      console.log("API Response:", result)

      // Handle different response formats
      let staffData: StaffMember[] = []

      if (result.data && Array.isArray(result.data)) {
        staffData = result.data
      } else if (Array.isArray(result)) {
        staffData = result
      } else {
        console.warn("Unexpected API response format:", result)
        staffData = []
      }

      setVaccinators(staffData)
    } catch (error: any) {
      console.error("Error fetching vaccinators:", error)
      setError(error.message || "Failed to load vaccinator data")
      toast({
        title: "Error",
        description: "Failed to load vaccinator data. Please refresh the page.",
        variant: "destructive",
      })
      // Set empty array on error to prevent filter issues
      setVaccinators([])
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    fetchVaccinators()
  }, [])

<<<<<<< HEAD
  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0]

      // Create preview
      const reader = new FileReader()
      reader.onload = (event) => {
        if (event.target && event.target.result) {
          setImagePreview(event.target.result as string)
        }
      }
      reader.readAsDataURL(file)
    }
  }

  const clearImage = () => {
    setImagePreview(null)
  }

  const closeForm = () => {
    setShowAddForm(false)
    form.reset()
    setImagePreview(null)
  }

  // Filter vaccinators based on search query
  const filteredVaccinators = vaccinators.filter(
    (vaccinator) =>
      `${vaccinator.first_name} ${vaccinator.last_name}`.toLowerCase().includes(searchQuery.toLowerCase()) ||
      vaccinator.department.toLowerCase().includes(searchQuery.toLowerCase()) ||
      vaccinator.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
      vaccinator.phone.toLowerCase().includes(searchQuery.toLowerCase()),
  )
=======
  // Filter vaccinators based on search query and status - with safety checks
  const filteredVaccinators = Array.isArray(vaccinators)
    ? vaccinators.filter((vaccinator) => {
        const matchesSearch =
          vaccinator.first_name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
          vaccinator.last_name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
          vaccinator.email?.toLowerCase().includes(searchQuery.toLowerCase()) ||
          vaccinator.specialization?.toLowerCase().includes(searchQuery.toLowerCase())

        const matchesStatus = filterStatus === "all" || vaccinator.status === filterStatus

        return matchesSearch && matchesStatus
      })
    : []
>>>>>>> 595bee3463104cee9216762a786993bc50791b83

  // Handle form submission
  async function onSubmit(values: VaccinatorFormValues) {
    setIsSubmitting(true)
    try {
<<<<<<< HEAD
      // Prepare data for API without complex destructuring
      const staffData = {
        first_name: values.firstName,
        last_name: values.lastName,
        email: values.email,
        phone: values.phone,
        department: values.departmentId,
        professional_id: values.professionalId,
        status: values.status,
        weekday_availability: values.weekdayAvailability,
        weekend_availability: values.weekendAvailability,
        profile_image_url: imagePreview || null,
        password: values.password, // Include password for auth user creation
      }

      // Use the server API route instead of direct Supabase client
=======
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
      const response = await fetch("/api/staff", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
<<<<<<< HEAD
        body: JSON.stringify(staffData),
      })

      if (!response.ok) {
        const contentType = response.headers.get("content-type")
        if (contentType && contentType.includes("application/json")) {
          const errorData = await response.json()
          throw new Error(errorData.error || `Failed to add vaccinator (${response.status})`)
        } else {
          throw new Error(`Failed to add vaccinator (${response.status})`)
        }
      }

      const result = await response.json()

      toast({
        title: "Vaccinator added successfully",
        description: `${values.firstName} ${values.lastName} has been added to the system.`,
      })

      // Create a new vaccinator object without complex spread operators
      const newVaccinator: StaffMember = {
        vaccinator_id: result.data.vaccinator_id,
        id: result.data.vaccinator_id, // For frontend compatibility
        auth_id: result.data.auth_id || undefined,
        first_name: values.firstName,
        last_name: values.lastName,
        email: values.email,
        phone: values.phone,
        department: values.departmentId,
        professional_id: values.professionalId,
        status: values.status,
        weekday_availability: values.weekdayAvailability,
        weekend_availability: values.weekendAvailability,
        profile_image_url: imagePreview || undefined,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }

      // Update the state with the new vaccinator using concat instead of spread
      setVaccinators((prevVaccinators) => [newVaccinator].concat(prevVaccinators))

      // Close the form
      closeForm()
    } catch (error: any) {
      console.error("Error adding vaccinator:", error)

      // Handle different types of errors
      let errorMessage = "Failed to add vaccinator. Please try again."

      if (error.message) {
        // If it's a standard Error object, use its message
        errorMessage = `Error: ${error.message}`

        // You could also handle specific error types
        if (error.message.includes("duplicate")) {
          errorMessage = "A vaccinator with this email already exists."
          form.setError("email", {
            type: "server",
            message: "This email is already registered in the system.",
          })
        } else if (error.message.includes("foreign key")) {
          errorMessage = "Invalid department selected."
          form.setError("departmentId", {
            type: "server",
            message: "Please select a valid department.",
          })
        }
      }

      toast({
        title: "Error",
        description: errorMessage,
=======
        body: JSON.stringify(values),
      })

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      toast({
        title: "Vaccinator added successfully",
        description: `Dr. ${values.first_name} ${values.last_name} has been added to the system.`,
      })

      fetchVaccinators() // Refresh the vaccinator list
      setDialogOpen(false)
      form.reset()
    } catch (error: any) {
      console.error("Error adding vaccinator:", error)
      toast({
        title: "Error",
        description: "Failed to add vaccinator. Please try again.",
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
        variant: "destructive",
      })
    } finally {
      setIsSubmitting(false)
    }
  }

<<<<<<< HEAD
  // Helper function to format availability for display
  const formatAvailability = (weekdays: boolean, weekends: boolean) => {
    if (weekdays && weekends) return "Weekdays, Weekends"
    if (weekdays) return "Weekdays"
    if (weekends) return "Weekends"
    return "Not available"
  }

  // Helper function to get badge variant based on status
  const getStatusBadgeVariant = (status: string) => {
    switch (status.toLowerCase()) {
=======
  // Helper function to get badge variant based on status
  const getStatusBadgeVariant = (status: string) => {
    switch (status?.toLowerCase()) {
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
      case "active":
        return "default"
      case "inactive":
        return "secondary"
<<<<<<< HEAD
      case "suspended":
        return "destructive"
=======
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
      default:
        return "outline"
    }
  }

<<<<<<< HEAD
  // Helper function to format status for display (capitalize first letter)
  const formatStatus = (status: string) => {
    return status.charAt(0).toUpperCase() + status.slice(1)
  }

  // Render empty state when there's an error
  const renderEmptyState = () => {
    if (error) {
      return (
        <div className="flex flex-col items-center justify-center p-8 text-center">
          <div className="text-red-500 mb-2">Error loading vaccinators</div>
          <p className="text-gray-500 mb-4">{error}</p>
        </div>
      )
    }

    return (
      <div className="flex flex-col items-center justify-center p-8 text-center">
        <p className="text-gray-500 mb-4">No vaccinators found</p>
      </div>
    )
  }
=======
  // Helper function to format status for display
  const formatStatus = (status: string) => {
    return status ? status.charAt(0).toUpperCase() + status.slice(1) : "Unknown"
  }

  // Safe calculation for stats
  const activeCount = Array.isArray(vaccinators) ? vaccinators.filter((v) => v.status === "active").length : 0
  const inactiveCount = Array.isArray(vaccinators) ? vaccinators.filter((v) => v.status === "inactive").length : 0
  const totalCount = Array.isArray(vaccinators) ? vaccinators.length : 0
  const specializationCount = Array.isArray(vaccinators) ? new Set(vaccinators.map((v) => v.specialization)).size : 0
>>>>>>> 595bee3463104cee9216762a786993bc50791b83

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <Link href="/admin/dashboard">
            <Button variant="ghost" size="icon">
              <ChevronLeft className="h-4 w-4" />
            </Button>
          </Link>
          <h2 className="text-2xl font-bold tracking-tight">Vaccinator Management</h2>
        </div>
      </div>

<<<<<<< HEAD
      <div className="flex items-center space-x-2">
        <Search className="h-4 w-4 text-gray-400" />
        <Input
          type="search"
          placeholder="Search vaccinators..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full max-w-sm"
        />
      </div>

      <div className="rounded-md border shadow-sm">
=======
      <div className="flex flex-wrap items-center gap-4">
        <Select onValueChange={setFilterStatus} defaultValue={filterStatus}>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Filter by status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="active">Active</SelectItem>
            <SelectItem value="inactive">Inactive</SelectItem>
          </SelectContent>
        </Select>

        <Button variant="outline" size="icon">
          <Filter className="h-4 w-4" />
        </Button>

        <div className="flex items-center gap-2 flex-1 md:max-w-sm ml-auto">
          <Search className="h-4 w-4 text-gray-400" />
          <Input
            type="search"
            placeholder="Search vaccinators..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full"
          />
        </div>
      </div>

      <div className="rounded-md border shadow-sm overflow-hidden">
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
<<<<<<< HEAD
              <TableHead>Department</TableHead>
              <TableHead>Contact</TableHead>
              <TableHead>Availability</TableHead>
=======
              <TableHead>Email</TableHead>
              <TableHead>Phone</TableHead>
              <TableHead>License</TableHead>
              <TableHead>Specialization</TableHead>
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
              <TableHead>Status</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              // Skeleton loading state
              Array(5)
                .fill(0)
                .map((_, index) => (
                  <TableRow key={`skeleton-${index}`}>
                    <TableCell>
<<<<<<< HEAD
                      <div className="flex items-center space-x-2">
                        <Skeleton className="h-10 w-10 rounded-full" />
                        <Skeleton className="h-4 w-[150px]" />
                      </div>
                    </TableCell>
                    <TableCell>
                      <Skeleton className="h-4 w-[100px]" />
=======
                      <Skeleton className="h-4 w-[150px]" />
                    </TableCell>
                    <TableCell>
                      <Skeleton className="h-4 w-[200px]" />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                    </TableCell>
                    <TableCell>
                      <Skeleton className="h-4 w-[120px]" />
                    </TableCell>
                    <TableCell>
                      <Skeleton className="h-4 w-[80px]" />
                    </TableCell>
                    <TableCell>
<<<<<<< HEAD
=======
                      <Skeleton className="h-4 w-[120px]" />
                    </TableCell>
                    <TableCell>
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                      <Skeleton className="h-6 w-[70px] rounded-full" />
                    </TableCell>
                    <TableCell>
                      <div className="flex space-x-2">
<<<<<<< HEAD
                        <Skeleton className="h-9 w-16" />
                        <Skeleton className="h-9 w-16" />
=======
                        <Skeleton className="h-9 w-9" />
                        <Skeleton className="h-9 w-9" />
                        <Skeleton className="h-9 w-9" />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                      </div>
                    </TableCell>
                  </TableRow>
                ))
<<<<<<< HEAD
            ) : filteredVaccinators.length > 0 ? (
              filteredVaccinators.map((vaccinator) => (
                <TableRow key={vaccinator.vaccinator_id || vaccinator.id}>
                  <TableCell>
                    <div className="font-medium">{`${vaccinator.first_name} ${vaccinator.last_name}`}</div>
                  </TableCell>
                  <TableCell>{vaccinator.department}</TableCell>
                  <TableCell>
                    <div className="flex flex-col">
                      <span>{vaccinator.email}</span>
                      <span className="text-sm text-gray-500">{vaccinator.phone}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    {formatAvailability(vaccinator.weekday_availability, vaccinator.weekend_availability)}
                  </TableCell>
=======
            ) : error ? (
              <TableRow>
                <TableCell colSpan={7} className="text-center py-8">
                  <div className="text-red-500 mb-2">Error loading data</div>
                  <p className="text-gray-500 mb-4">{error}</p>
                  <Button onClick={fetchVaccinators} variant="outline">
                    Try Again
                  </Button>
                </TableCell>
              </TableRow>
            ) : filteredVaccinators.length > 0 ? (
              filteredVaccinators.map((vaccinator) => (
                <TableRow key={vaccinator.id}>
                  <TableCell>
                    <div className="font-medium">
                      Dr. {vaccinator.first_name} {vaccinator.last_name}
                    </div>
                  </TableCell>
                  <TableCell>{vaccinator.email}</TableCell>
                  <TableCell>{vaccinator.phone}</TableCell>
                  <TableCell>{vaccinator.license_number}</TableCell>
                  <TableCell>{vaccinator.specialization}</TableCell>
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                  <TableCell>
                    <Badge variant={getStatusBadgeVariant(vaccinator.status)}>{formatStatus(vaccinator.status)}</Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex space-x-2">
<<<<<<< HEAD
                      <Button variant="outline" size="sm">
                        Edit
                      </Button>
                      <Button variant="outline" size="sm" className="text-red-500 hover:text-red-600">
                        Delete
=======
                      <Button variant="ghost" size="sm">
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm">
                        <Edit className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="sm" className="text-red-500 hover:text-red-600">
                        <Trash2 className="h-4 w-4" />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))
            ) : (
              <TableRow>
<<<<<<< HEAD
                <TableCell colSpan={6} className="text-center py-4">
                  {renderEmptyState()}
=======
                <TableCell colSpan={7} className="text-center py-8">
                  <div className="text-gray-500">No vaccinators found</div>
                  {searchQuery && (
                    <p className="text-sm text-gray-400 mt-2">Try adjusting your search or filter criteria</p>
                  )}
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>

      <div className="flex items-center justify-between">
        <p className="text-sm text-gray-500">
<<<<<<< HEAD
          Showing {filteredVaccinators.length} of {vaccinators.length} vaccinators
=======
          Showing {filteredVaccinators.length} of {totalCount} vaccinators
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
        </p>
        <div className="space-x-2">
          <Button variant="outline" size="sm" disabled>
            Previous
          </Button>
          <Button variant="outline" size="sm" disabled>
            Next
          </Button>
        </div>
      </div>

<<<<<<< HEAD
=======
      <Card>
        <CardHeader>
          <CardTitle>Staff Summary</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/4" />
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-green-600">{activeCount}</div>
                <div className="text-sm text-gray-500">Active</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-gray-600">{inactiveCount}</div>
                <div className="text-sm text-gray-500">Inactive</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">{totalCount}</div>
                <div className="text-sm text-gray-500">Total Staff</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-purple-600">{specializationCount}</div>
                <div className="text-sm text-gray-500">Specializations</div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

>>>>>>> 595bee3463104cee9216762a786993bc50791b83
      {/* Floating Action Button */}
      <Button
        className="h-14 w-14 rounded-full fixed bottom-8 right-8 shadow-lg flex items-center justify-center"
        size="icon"
<<<<<<< HEAD
        onClick={() => setShowAddForm(true)}
=======
        onClick={() => setDialogOpen(true)}
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
      >
        <Plus className="h-6 w-6" />
      </Button>

<<<<<<< HEAD
      {/* Add Vaccinator Dialog */}
      <Dialog open={showAddForm} onOpenChange={setShowAddForm}>
        <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add New Vaccinator</DialogTitle>
            <DialogDescription>Enter the details for the new vaccinator to create their account.</DialogDescription>
=======
      {/* Add New Vaccinator Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add New Staff Member</DialogTitle>
            <DialogDescription>Enter the details for the new staff member to add to the system.</DialogDescription>
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
          </DialogHeader>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
<<<<<<< HEAD
              {/* Profile Image */}
              <FormSection title="Profile Image">
                <div className="flex items-center gap-4">
                  <div className="border-2 border-dashed rounded-md border-gray-300 w-32 h-32 flex flex-col items-center justify-center relative">
                    {imagePreview ? (
                      <>
                        <img
                          src={imagePreview || "/placeholder.svg"}
                          alt="Profile preview"
                          className="w-full h-full object-cover rounded-md"
                        />
                        <button
                          type="button"
                          onClick={clearImage}
                          className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </>
                    ) : (
                      <>
                        <Upload className="h-8 w-8 text-gray-400" />
                        <p className="text-xs text-center text-gray-500 mt-2">
                          Drag your image here
                          <br />
                          (jpg and png accepted)
                        </p>
                      </>
                    )}
                  </div>
                  <div>
                    <Input
                      id="profileImage"
                      type="file"
                      accept="image/jpeg,image/png"
                      className="hidden"
                      onChange={handleImageChange}
                      disabled={isSubmitting}
                    />
                    <Label htmlFor="profileImage" asChild>
                      <Button type="button" variant="outline" className="cursor-pointer" disabled={isSubmitting}>
                        Browse...
                      </Button>
                    </Label>
=======
              <FormSection title="Profile Image">
                <div className="flex items-center space-x-4">
                  <Avatar className="h-20 w-20">
                    <AvatarImage src={form.getValues("image_url") || "/placeholder-avatar.jpg"} />
                    <AvatarFallback>
                      {form.getValues("first_name") ? form.getValues("first_name")?.charAt(0) : "U"}
                      {form.getValues("last_name") ? form.getValues("last_name")?.charAt(0) : "U"}
                    </AvatarFallback>
                  </Avatar>
                  <div>
                    <FormField
                      control={form.control}
                      name="image_url"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Image URL</FormLabel>
                          <FormControl>
                            <Input placeholder="Enter image URL" disabled={isSubmitting} {...field} />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                  </div>
                </div>
              </FormSection>

<<<<<<< HEAD
              {/* Basic Information */}
              <FormSection title="Basic Information">
                <div className="grid gap-4 md:grid-cols-2">
                  <FormField
                    control={form.control}
                    name="firstName"
=======
              <FormSection title="Basic Information">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="first_name"
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>First Name</FormLabel>
                        <FormControl>
<<<<<<< HEAD
                          <Input placeholder="John" disabled={isSubmitting} {...field} />
=======
                          <Input placeholder="e.g., Sarah" disabled={isSubmitting} {...field} />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
<<<<<<< HEAD
                    name="lastName"
=======
                    name="last_name"
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Last Name</FormLabel>
                        <FormControl>
<<<<<<< HEAD
                          <Input placeholder="Doe" disabled={isSubmitting} {...field} />
=======
                          <Input placeholder="e.g., Johnson" disabled={isSubmitting} {...field} />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
<<<<<<< HEAD

                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="departmentId"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Department</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting}>
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select department" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="pediatric">Pediatric</SelectItem>
                            <SelectItem value="general">General</SelectItem>
                            <SelectItem value="infectious">Infectious Disease</SelectItem>
                            <SelectItem value="immunology">Immunology</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="status"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Status</FormLabel>
                        <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting}>
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select status" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            <SelectItem value="active">Active</SelectItem>
                            <SelectItem value="inactive">Inactive</SelectItem>
                            <SelectItem value="suspended">Suspended</SelectItem>
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <FormField
                  control={form.control}
                  name="professionalId"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Professional ID/License</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., MD12345" disabled={isSubmitting} {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </FormSection>

              {/* Contact Information */}
=======
              </FormSection>

>>>>>>> 595bee3463104cee9216762a786993bc50791b83
              <FormSection title="Contact Information">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="email"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Email</FormLabel>
                        <FormControl>
                          <Input
                            type="email"
<<<<<<< HEAD
                            placeholder="doctor@lavihospital.com"
=======
                            placeholder="e.g., sarah.johnson@lavihospital.com"
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                            disabled={isSubmitting}
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="phone"
                    render={({ field }) => (
                      <FormItem>
<<<<<<< HEAD
                        <FormLabel>Phone Number</FormLabel>
                        <FormControl>
                          <Input type="tel" placeholder="+1 (555) 123-4567" disabled={isSubmitting} {...field} />
=======
                        <FormLabel>Phone</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., +1 (555) 123-4567" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <div className="grid grid-cols-1 gap-4">
                  <FormField
                    control={form.control}
                    name="address"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Address</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., 123 Main St" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <FormField
                    control={form.control}
                    name="city"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>City</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., Anytown" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="state"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>State</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., CA" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="zip"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Zip Code</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., 90210" disabled={isSubmitting} {...field} />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </FormSection>

<<<<<<< HEAD
              {/* Availability */}
              <FormSection title="Availability" description="Select when the vaccinator is available">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="weekdayAvailability"
                    render={({ field }) => (
                      <FormItem className="flex flex-row items-start space-x-2 space-y-0">
                        <FormControl>
                          <Checkbox checked={field.value} onCheckedChange={field.onChange} disabled={isSubmitting} />
                        </FormControl>
                        <div className="space-y-1 leading-none">
                          <FormLabel>Weekdays (Monday-Friday)</FormLabel>
                        </div>
=======
              <FormSection title="Professional Information">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="license_number"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>License Number</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., MD12345" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
<<<<<<< HEAD
                    name="weekendAvailability"
                    render={({ field }) => (
                      <FormItem className="flex flex-row items-start space-x-2 space-y-0">
                        <FormControl>
                          <Checkbox checked={field.value} onCheckedChange={field.onChange} disabled={isSubmitting} />
                        </FormControl>
                        <div className="space-y-1 leading-none">
                          <FormLabel>Weekends (Saturday-Sunday)</FormLabel>
                        </div>
=======
                    name="specialization"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Specialization</FormLabel>
                        <FormControl>
                          <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select specialization" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="Internal Medicine">Internal Medicine</SelectItem>
                              <SelectItem value="Pediatrics">Pediatrics</SelectItem>
                              <SelectItem value="Family Medicine">Family Medicine</SelectItem>
                              <SelectItem value="Emergency Medicine">Emergency Medicine</SelectItem>
                              <SelectItem value="Infectious Disease">Infectious Disease</SelectItem>
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="department"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Department</FormLabel>
                        <FormControl>
                          <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select department" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="General Medicine">General Medicine</SelectItem>
                              <SelectItem value="Pediatric Medicine">Pediatric Medicine</SelectItem>
                              <SelectItem value="Family Practice">Family Practice</SelectItem>
                              <SelectItem value="Emergency Department">Emergency Department</SelectItem>
                              <SelectItem value="Vaccination Center">Vaccination Center</SelectItem>
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="status"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Status</FormLabel>
                        <FormControl>
                          <Select onValueChange={field.onChange} defaultValue={field.value} disabled={isSubmitting}>
                            <SelectTrigger>
                              <SelectValue placeholder="Select status" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="active">Active</SelectItem>
                              <SelectItem value="inactive">Inactive</SelectItem>
                            </SelectContent>
                          </Select>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <div className="grid grid-cols-1 gap-4">
                  <FormField
                    control={form.control}
                    name="availability"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Availability</FormLabel>
                        <FormControl>
                          <Textarea placeholder="Enter availability details" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                      </FormItem>
                    )}
                  />
                </div>
              </FormSection>

<<<<<<< HEAD
              {/* Security */}
              <FormSection title="Account Security">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
=======
              <FormSection title="Security">
                <div className="grid grid-cols-2 gap-4">
                  <FormField
                    control={form.control}
                    name="username"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Username</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter username" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                    name="password"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Password</FormLabel>
                        <FormControl>
<<<<<<< HEAD
                          <Input type="password" placeholder="••••••••" disabled={isSubmitting} {...field} />
                        </FormControl>
                        <FormDescription>
                          Must be at least 8 characters long, contain one uppercase letter, one number, and one special
                          character
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="confirmPassword"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Confirm Password</FormLabel>
                        <FormControl>
                          <Input type="password" placeholder="••••••••" disabled={isSubmitting} {...field} />
=======
                          <Input type="password" placeholder="Enter password" disabled={isSubmitting} {...field} />
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </FormSection>

              <DialogFooter>
<<<<<<< HEAD
                <Button type="button" variant="outline" onClick={closeForm} disabled={isSubmitting}>
=======
                <Button type="button" variant="outline" onClick={() => setDialogOpen(false)} disabled={isSubmitting}>
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                  Cancel
                </Button>
                <Button type="submit" disabled={isSubmitting}>
                  {isSubmitting ? (
                    <>
                      <svg
                        className="animate-spin -ml-1 mr-2 h-4 w-4"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                      >
                        <circle
                          className="opacity-25"
                          cx="12"
                          cy="12"
                          r="10"
                          stroke="currentColor"
                          strokeWidth="4"
                        ></circle>
                        <path
                          className="opacity-75"
                          fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                        ></path>
                      </svg>
<<<<<<< HEAD
                      Adding Vaccinator...
                    </>
                  ) : (
                    "Add Vaccinator"
=======
                      Adding Staff Member...
                    </>
                  ) : (
                    "Add Staff Member"
>>>>>>> 595bee3463104cee9216762a786993bc50791b83
                  )}
                </Button>
              </DialogFooter>
            </form>
          </Form>
        </DialogContent>
      </Dialog>
    </div>
  )
}
